# Generated by Django 4.0.3 on 2022-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_roles_remove_usuario_isadmin_usuario_usuarios_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios_roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Normal'), ('3', 'Lectura'), ('4', 'Aprobador/Risk Manager'), ('5', 'CAB')], max_length=50, null=True, verbose_name='Roles de Usuario'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
