# Generated by Django 4.0.3 on 2022-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_usuarios_roles_usuario_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=60, verbose_name='Roles')),
                ('descripcion', models.TextField(verbose_name='Descripcion del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuarios_roles',
            field=models.ManyToManyField(blank=True, to='usuario.roles'),
        ),
    ]
