# Generated by Django 4.0.3 on 2022-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_roles_remove_usuario_roles_usuario_usuarios_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios_roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rol de Usuario'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
