# Generated by Django 4.0.3 on 2022-03-10 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='EstadosRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado de Riesgo')),
            ],
            options={
                'verbose_name': 'Estado de Riesgo',
                'verbose_name_plural': 'Estados de Riesgos',
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estrategia', models.CharField(max_length=200, verbose_name='Estrategia')),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
            },
        ),
        migrations.CreateModel(
            name='FuenteRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Fuente de Riesgos')),
            ],
            options={
                'verbose_name': 'Fuente de Riesgo',
                'verbose_name_plural': 'Fuentes de Riesgos',
            },
        ),
        migrations.CreateModel(
            name='KRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_kri', models.TextField(verbose_name='KRI')),
            ],
            options={
                'verbose_name': 'KRI',
                'verbose_name_plural': 'KRI',
            },
        ),
        migrations.CreateModel(
            name='MagnitudImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Magnitud de Impacto')),
            ],
            options={
                'verbose_name': 'Magnitud de impacto',
                'verbose_name_plural': 'Magnitud de impactos',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Tipos_KRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.TextField(verbose_name='KRI')),
            ],
            options={
                'verbose_name': 'Tipo de KRI',
                'verbose_name_plural': 'Tipos de KRI',
            },
        ),
        migrations.CreateModel(
            name='TiposServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Tipo de Servicios')),
            ],
            options={
                'verbose_name': 'Tipo Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Servicios')),
                ('tipos_servicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.tiposservicios')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(max_length=200, verbose_name='Riesgo')),
                ('fecha_registro_riesgo', models.DateField(null=True, verbose_name='Fecha de Registro del Riesgo')),
                ('escenario_riesgo', models.CharField(max_length=350, verbose_name='Escenario Riesgo')),
                ('activos_afectados', models.CharField(blank=True, max_length=100, verbose_name='Activos Afectados')),
                ('impacto', models.CharField(max_length=50, verbose_name='Impacto')),
                ('probabilidad_ocurrencia', models.CharField(max_length=50, verbose_name='Probabilidad Ocurrencia')),
                ('nivel_riesgo', models.CharField(max_length=250, verbose_name='Nivel de Riesgo')),
                ('control', models.TextField(blank=True, verbose_name='Control')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('importancia', models.TextField(blank=True, verbose_name='Importancia')),
                ('form_ident_riesgo', models.CharField(max_length=15, verbose_name='Forma de Identificación del Riesgo')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('categorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.categorias')),
                ('estados_riesgos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.estadosriesgos')),
                ('estrategia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.estrategia')),
                ('fuente_riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.fuenteriesgos')),
                ('kri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.kri')),
                ('magnitud_impacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.magnitudimpacto')),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.propietario')),
                ('riesgos_servicios', models.ManyToManyField(blank=True, to='riesgos.servicios')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
            },
        ),
        migrations.AddField(
            model_name='kri',
            name='tipos_kri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.tipos_kri'),
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_incidente', models.DateField(null=True, verbose_name='Fecha de Registro del Incidente')),
                ('riesgos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riesgos.riesgos')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
    ]
