# Generated by Django 4.0.3 on 2022-04-07 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 12, 27, 32, 785820), verbose_name='Fecha'),
        ),
    ]
