# Generated by Django 4.0.3 on 2022-04-07 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_alter_comentarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 12, 38, 16, 823049), verbose_name='Fecha'),
        ),
    ]
