# Generated by Django 4.0.3 on 2022-03-15 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_comentarios_alter_estadosriesgos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riesgos',
            name='nivel_riesgo',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 10, 21, 30, 760758), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='riesgos',
            name='impacto',
            field=models.CharField(choices=[('1', 'Insignificante'), ('2', 'Menor'), ('3', 'Significante'), ('4', 'Mayor'), ('5', 'Severo')], max_length=50, verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='riesgos',
            name='probabilidad_ocurrencia',
            field=models.CharField(choices=[('1', 'Improbable'), ('2', 'Raro'), ('3', 'Moderado'), ('4', 'Probable'), ('5', 'Casi Cierto')], max_length=50, verbose_name='Probabilidad Ocurrencia'),
        ),
    ]
