# Generated by Django 4.0.3 on 2022-03-16 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0004_alter_comentarios_options_riesgos_comentario_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 14, 21, 41, 433469), verbose_name='Fecha'),
        ),
    ]
