# Generated by Django 4.0.3 on 2022-03-17 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0006_alter_comentarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 13, 52, 59, 695809), verbose_name='Fecha'),
        ),
    ]
