# Generated by Django 4.0.3 on 2022-03-29 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0009_remove_riesgos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 16, 33, 57, 234972), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='riesgos',
            name='riesgos_servicios',
            field=models.ManyToManyField(blank=True, null=True, to='riesgos.servicios'),
        ),
    ]
