# Generated by Django 4.0.3 on 2022-03-30 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0010_alter_comentarios_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riesgos',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 13, 56, 57, 106366), verbose_name='Fecha'),
        ),
        migrations.DeleteModel(
            name='Incidentes',
        ),
    ]
